---
- hosts: ~^arista
  gather_facts: no

  vars:
    dnsserver: "8.8.8.8"

  tasks:
  - name: Configure DNS
    cli_config:
      config: ip name-server {{ dnsserver }}

  - name: Check config
    cli_command:
      command: sh run | i ip name-server
    register: results

  - name: print output
    debug:
      var: results.stdout
    tags:
      - never
      - showresults

  - set_fact:
      expected_output: "ip name-server vrf default {{ dnsserver }}"

  - fail:
      msg: failing
    when: expected_output not in results.stdout
