---
- hosts: ~^arista
  gather_facts: no

  vars:
    dnsserver: "8.8.8.8"

  tasks:
  - name: Configure DNS
    cli_config:
      config: ip name-server {{ dnsserver }}

  - name: Check config
    cli_command:
      command: sh run | i ip name-server

  - name: print output
    debug:
      var: results.stdout
