---
- hosts: localhost
  gather_facts: no

  vars:
    simpson: "{{ lookup('URL','https://thesimpsonsquoteapi.glitch.me/quotes') }}"

  tasks:
    - name: use copy to create file
      copy:
        content: "{{ simpson[0].quote }} \n {{ simpson[0].character \n }}"
        dest: simpsons-ans.txt
