---
- name: Error Handling
  hosts: planetexpress

  tasks:
    - block:
       - shell: "echo 'My single task ran' > example.txt"
       - shell: "echo 'My second task ran' >> example.txt"
       - shell: "/bin/false"
      rescue:
       - shell: "echo 'My rescue code ran' >> example.txt"
      always:
       - shell: "echo 'This always runs' >> example.txt"
